apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen3-32b-pd-tp2-d960e4-sim
spec:
  selector:
    app: vllm-qwen3-32b-pd-tp2-d960e4-sim-decode
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
