apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen3-32b-pd-525604-decode
spec:
  selector:
    app: vllm-qwen3-32b-pd-525604-decode
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: nixl-side
    port: 5601
    targetPort: 5601
  type: ClusterIP
