apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen3-32b-pd-72d33f-real
spec:
  selector:
    app: vllm-qwen3-32b-pd-72d33f-real-decode
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
