apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen3-32b-pd-72d33f-sim-prefill
spec:
  selector:
    app: vllm-qwen3-32b-pd-72d33f-sim-prefill
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: nixl-side
    port: 5600
    targetPort: 5600
  type: ClusterIP
